name: docker-build

on:
  push:
    branches:
      - 'main'
      - 'master'
  repository_dispatch:
    types: [ build ]

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: spiretf/docker-spire-server:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
